# Generated by Django 3.2.9 on 2021-11-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=40)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.state')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Prefer Not To Say')], max_length=1)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=60)),
                ('mother_name', models.CharField(blank=True, max_length=60)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='census.district')),
            ],
        ),
    ]
