# Generated by Django 3.2.9 on 2021-11-27 09:07

import census.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20211127_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=50)),
                ('mimeType', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to=census.models.renaming_uploaded_file2)),
            ],
        ),
    ]
